# Generated by Django 3.1.5 on 2021-02-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='FailedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('topic_name', models.CharField(max_length=255)),
                ('subscription_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.JSONField()),
                ('exception_str', models.TextField()),
                ('traceback', models.TextField()),
                ('correlation_id', models.CharField(blank=True, max_length=36)),
            ],
        ),
    ]
