# Generated by Django 3.2.7 on 2021-10-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedPublishMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('data_version', models.CharField(max_length=255)),
                ('event_time', models.DateTimeField()),
                ('data', models.JSONField()),
                ('correlation_id', models.CharField(blank=True, max_length=36)),
            ],
        ),
    ]
